DB_HOST=127.0.0.1
DB_PORT=3307
DB_NAME=project
DB_USERNAME=root
DB_PASSWORD=root

JWT_SECRET=KJ5V7oXO1ddz_utM0Y1ATqa9klyETrc6z9SRjrOB87k

REDIS_HOST=redis-server
REDIS_PORT=6379
REDIS_PASSWORD=123456@

EMAIL_USERNAME=vitcon202205@gmail.com
EMAIL_PASSWORD=Vitcon2005@