spring:
  config:
    import: optional:application-env.yml

  datasource:
    url: jdbc:mysql://127.0.0.1:3006/itpath
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis-server
      port: 6379
      password: 123456@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  jackson:
    time-zone: Asia/Ho_Chi_Minh
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: fc718a3262b759
    password: 4514719c205a70
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

